apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lunch-rush-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: lunch-rush-api-svc
            port:
              number: 80
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: lunch-rush-api-svc
            port:
              number: 80
